## Activation Function

In [1]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [3]:
sigmoid(1)

0.7310585786300049

In [4]:
sigmoid(-89)

2.2273635617957434e-39

In [5]:
def tanh(x):
    return (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))

In [ ]:
tan

## Matrix Multiplication

In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [4]:
price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [6]:
np.dot(price_per_unit, units)

array([34400, 50000, 64400])

## Cost Function

### MAE

In [7]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [14]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total error: ", total_error) 
    mae = total_error / len(y_true)
    print("MAE: ", mae) 
    return mae

In [15]:
mae(y_true, y_predicted)

Total error:  2.5
MAE:  0.5


0.5

In [17]:
np.mean(np.abs(y_predicted - y_true))

0.5

### Log Loss

In [18]:
np.log(0)

c:\users\ag20459\appdata\local\continuum\anaconda3\envs\codebasics\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [19]:
epsilion = 1e-15

In [24]:
y_predicted_new  = [max(i,epsilion) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [25]:
y_predicted_new  = [min(i,1-epsilion) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [26]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [27]:
-np.mean(y_true * np.log(y_predicted_new)+ (1-y_true) * np.log(1-y_predicted_new))

17.2696280766844

In [30]:
def log_loss(y_true, y_predicted):
    epsilion = 1e-15
    y_predicted_new = [max(i,epsilion) for i in y_predicted]
    y_predicted_new  = [min(i,1-epsilion) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new)+ (1-y_true) * np.log(1-y_predicted_new))

In [31]:
log_loss(y_true, y_predicted)

17.2696280766844

### MSE